# Generated by Django 4.0.1 on 2022-02-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_tag_produit_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prix',
            new_name='price',
        ),
    ]
