# Generated by Django 4.0.1 on 2022-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_tag_produit_tag'),
        ('commande', '0002_commande_client_commande_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(to='produit.Produit'),
        ),
    ]
