# Generated by Django 4.0.1 on 2022-02-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_rename_prix_produit_price'),
        ('commande', '0003_remove_commande_produit_commande_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.produit'),
        ),
    ]
